version: 2

project_name: pushback

builds:
  - id: darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goamd64:
      - v2
      - v3
      - v4
    goarm:
      - "5"
      - "6"
      - "7"
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: windows
    main: .
    goos:
      - windows
    goarch:
      - amd64
      - "386"
    goamd64:
      - v2
      - v3
      - v4
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: freebsd
    main: .
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: mipsle
    main: .
    goos:
      - linux
    goarch:
      - mipsle
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: mips
    main: .
    goos:
      - linux
    goarch:
      - mips
    gomips:
      - hardfloat
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

  - id: mips64
    main: .
    goos:
      - linux
    goarch:
      - mips64
      - mips64le
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    format: tar.gz
    files:
      - src: deploy/pushback.p8
        dst: pushback.p8
      - src: deploy/data/config.yaml
        dst: config.yaml
      - LICENSE
      - README.md
      - README_EN.md
      - README_KO.md
      - README_JA.md

release:
  github:
    owner: uuneo
    name: pushback-server

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
