name: Build And Push

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        id: vars
        run: |
          echo "build_version=$(git describe --tags)" | tee -a $GITHUB_ENV >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%d-%H:%M:%S')" | tee -a $GITHUB_ENV >> $GITHUB_OUTPUT
          echo "commit_id=$(git rev-parse --short HEAD)" | tee -a $GITHUB_ENV >> $GITHUB_OUTPUT

      - name: Debug Tags
        run: git tag -l

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/arm/v7
            linux/arm64
            linux/amd64
          build-args: |
            VERSION=${{ steps.vars.outputs.build_version }}
            BUILD_DATE=${{ steps.vars.outputs.build_date }}
            COMMIT_ID=${{ steps.vars.outputs.commit_id }}
          tags: |
            sunvx/pushback:latest
            sunvx/pushback:${{ env.build_version }}
            ghcr.io/uuneo/pushback:latest
            ghcr.io/uuneo/pushback:${{ env.build_version }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}